### ISSUE TITLE
Selecting a State in StateLevel no longer zooms onto it

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/NESP2#141]
Also: 

- clicking on the state button in village level doesn't bring you back to the state view. 
- Clicking on a neighboring state doesn't zoom onto it. 
- After clicking on a neighboring state clusters in there are not selectable
- After clicking on a neighboring state it is not posible to reselect the previous state

**Comment by Bachibouzouk** [comment]
Ouch, it seems it is not as easy as first thought

**Comment by Bachibouzouk** [comment]
@christian-rli, @catcad It was because the geoJSON was not updated anymore since I introduced the restriction of the zoom function when coming back from the village level. The previous state was still not present as a feature. But I forgot that one could come from the state level to the state level. Now it is fixed :)
