### ISSUE TITLE
Filter ranges are not helpful

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2#167]
Is it possible that the max filter values can be set to the respective state level maximum?

**Comment by christian-rli** [comment]
Adapt slider range to reasonable steps in every area.

**Comment by christian-rli** [comment]
Minimum/Maximum Values

identified settlements:
area_km2: 0.01 / 1052 (19 clusters go above 100)
grid_dist_km: 0/49.9999

ogclusters:
area_km2: 0.01/3.3
grid_dist_km: 0.98/46
building_count: 7/10269 (5 go above 5000)
percentage_building_area: 0.003/1

I will implement reasonable steps in the slider so that selection in every range is useful.

**Comment by christian-rli** [comment]
identified settlements:
area_km2: 
    'min': [0, 0.05],
    '40%': [1, 0.5],
    '70%': [10, 1],
    '90%': [100, 100],
    'max': 1100,

grid_dist_km:
    'min': [0, 0.1],
    '20%': [1, 0.5],
    '50%': [10, 1],
    'max': 50,

**Comment by christian-rli** [comment]
area_km2:
    'min': [0, 0.01],
    '70%': [0.5, 0.05],
    'max': 3.5,

grid_dist_km: 
    'min': [0, 0.1],
    '25%': [5, 0.5],
    '75%': [10, 1],
    'max': 50,

building_count: 
    'min': [0, 1],
    '10%': [10, 1],
    '30%': [100, 10],
    '80%': [1000, 100],
    'max': 11000,

percentage_building_area: 
    'min': [0, 0.01],
    '50%': [0.1, 0.01],
    '75%': [0.2, 0.05],
    'max': 1,
